version: '3.8'

services:
  db:
    image: postgres
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kantor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer1234
    volumes:
      - C:/postgres_datapart:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: kantorapp_container
    ports:
      - "8089:8089"
    environment:
      db-url: jdbc:postgresql://db:5432/kantor
      db-username: postgres
      db-password: qwer1234
    depends_on:
      - db
    restart: always
